const offerLink = "vnd.youtube://www.youtube.com/redirect?event=comments&redir_token=QUFFLUhqblBUeHhVOGZjM1ZuS3owNkFPaGFsT0tSZHkyUXxBQ3Jtc0traFRGT1BUV3lzMHZwZEdFWHFkXzJtVThXcnNRRkNRaXlqUkxXU2dWbWIzeFBEX0xOTFF3S0RPZW94QjBlTXoySGNDUFRnMGNXQjUxZzV0a1dfV21TQ2NXS2hHZEd6cGV4VWtIRW1JSldFcXozcENONA&q=https%3A%2F%2Fdirect.me%2Fl%2Fcbf4&html_redirect=1 ";


